server:
  port: 8081

spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 5000
    port: 6379
    database: 0
    host: 127.0.0.1


